### ISSUE TITLE
Where are images??

### ISSUE THREAD

**Issue by james-sands** [AnthonyW2/Pearson-eBook-Downloader#1]
After the program has run and the page no longer refreshes, the files are no where to be found? Please help :))

**Comment by AnthonyW2** [comment]
They should be in your downloads folder.
Which browser are you using?
Are any downloads initialised when you press "Download Pages"?

**Comment by james-sands** [comment]
I'm using chrome, and no downloads are initialised when I press download pages. thanks for your help

**Comment by james-sands** [comment]
Nevermind, this is completely user error hahaha

**Comment by AnthonyW2** [comment]
Ah, ok. Good to know.
If the instructions aren't clear enough, feel free to suggest changes
